// src/Board.tsx
import React, { useEffect, useRef, useMemo, useState, RefObject, MouseEvent } from 'react';
import styled from 'styled-components';
import Mosaic from './utils/mosaicClass';
import { PinShape, GridColors } from './utils/mosaicTypes';

type Props = {
    pinsCountW: number;
    pinsCountH: number;
    pinSize: number;
    pinShape: PinShape;
    boardPadding?: number;
    pinsColors?: GridColors | null;
    pinPadding?: number;
    emptyColor?: string;
};
export const StyledBoardCnt = styled.div`
    display: flex;
    justify-content: center;
    canvas {
        cursor: pointer;
    }
`;
export default function Board({
    pinsCountW,
    pinsCountH,
    pinSize,
    pinShape,
    boardPadding = 5,
    pinsColors = null,
    pinPadding = 0,
    emptyColor,
}: Props) {
    const boardRef = useRef(null) as RefObject<HTMLCanvasElement>;

    const [selectedRow, setSelectedRow] = useState(-1);
    const [selectedCol, setSelectedCol] = useState(-1);

    const mosaic = useMemo(
        () =>
            new Mosaic({
                pinShape,
                pinSize,
                pinsCountW,
                pinsCountH,
                pinsColors,
                pinPadding,
                emptyColor,
                boardPaddingW: boardPadding,
                boardPaddingH: boardPadding,
            }),
        [
            pinShape,
            pinSize,
            pinsCountW,
            pinsCountH,
            boardPadding,
            pinsColors,
            pinPadding,
            emptyColor,
        ],
    );

    useEffect(() => {
        if (!boardRef.current) {
            return;
        }
        const ctx = boardRef.current.getContext('2d');
        if (ctx === null) {
            return;
        }

        mosaic.drawBoard({
            ctx,
            selectedCol,
            selectedRow,
        });
    }, [mosaic, selectedRow, selectedCol]);

    return (
        <StyledBoardCnt>
            <canvas
                ref={boardRef}
                width={mosaic.getBoardWidth()}
                height={mosaic.getBoardHeight()}
                onMouseMove={(event) =>
                    _calculateSelectedCell(event, mosaic, setSelectedRow, setSelectedCol)
                }
                onMouseLeave={() => _clearSelectedCell(setSelectedRow, setSelectedCol)}
            />
        </StyledBoardCnt>
    );
}

function _calculateSelectedCell(
    event: MouseEvent,
    mosaic: Mosaic,
    setSelectedRow: React.Dispatch<React.SetStateAction<number>>,
    setSelectedCol: React.Dispatch<React.SetStateAction<number>>,
) {
    const canvas = event.target as HTMLCanvasElement;
    const rect = canvas.getBoundingClientRect();
    const mouseX = event.clientX - rect.left;
    const mouseY = event.clientY - rect.top;

    const [row, col] = mosaic.getCellIndsByMouse(mouseX, mouseY);
    setSelectedCol(col);
    setSelectedRow(row);
}
function _clearSelectedCell(
    setSelectedRow: React.Dispatch<React.SetStateAction<number>>,
    setSelectedCol: React.Dispatch<React.SetStateAction<number>>,
) {
    setSelectedCol(-1);
    setSelectedRow(-1);
}

// src/components/Board.vue
<template>
  <canvas ref='canvas' class='app-board' width=500 :height=500 @mousemove="onHover" @mouseleave="onMouseLeave" />
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue'
import { PinShape, MosaicSize } from '../utils/mosaicTypes'
import Mosaic from '@/utils/mosaicClass';

const sizeSettings = {
  xs: 100,
  s: 60,
  m: 50,
  l: 40
}

export default defineComponent({
  name: 'app-board',
  props: {
    pinShape: {
      required: false,
      type: String as PropType<PinShape>,
      default: 'round'
    },
    size: {
      required: false,
      type: String as PropType<MosaicSize>,
      default: 'm'
    }
  },
  data: () => ({
    selectedCol: -1,
    selectedRow: -1
  }),
  computed: {
    canvasWidth (): number {
      return 500;
    },
    canvasHeight (): number {
      return 500;
    },
    pinsSize (): number {
      return sizeSettings[this.size];
    },
    mosaicObject (): Mosaic {
      return new Mosaic({
        width: this.canvasWidth,
        height: this.canvasHeight,
        pinShape: this.pinShape,
        pinSize: this.pinsSize
      });
    }
  },
  methods: {
    onHover (event: MouseEvent) {
      const canvas = this.$refs.canvas as HTMLCanvasElement;
      const rect = canvas.getBoundingClientRect();
      const mouseX = event.clientX - rect.left;
      const mouseY = event.clientY - rect.top;

      const [row, col] = this.mosaicObject.getCellIndsByMouse(mouseX, mouseY);
      this.selectedCol = col;
      this.selectedRow = row;
    },
    onMouseLeave () {
      this.selectedCol = -1;
      this.selectedRow = -1;
    },
    redrawBoard () {
      const canvas = this.$refs.canvas as HTMLCanvasElement;
      const ctx = canvas.getContext('2d');
      if (ctx === null) return;

      this.mosaicObject.drawBoard({
        ctx,
        selectedCol: this.selectedCol,
        selectedRow: this.selectedRow
      });
    }
  },
  watch: {
    selectedCol () {
      this.redrawBoard();
    },
    selectedRow () {
      this.redrawBoard();
    },
    pinShape () {
      this.redrawBoard();
    },
    size () {
      this.redrawBoard();
    }
  },
  mounted (): void {
    this.redrawBoard();
  }
})
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.app-board {
  cursor: pointer;
  margin: 1rem;
}
</style>
