// src/toolPanel/ToolPanel.tsx
import React from 'react';
import styled from 'styled-components';
import SizeSelect from './SizeSelect';
import ShapeSelect from './ShapeSelect';
import PinPicker from '../pinPicker/PinPicker';

const StyledToolsCnt = styled.div`
    background-color: ${(props) => props.theme.bgColor};
    padding: 1rem;
    display: flex;
    justify-content: center;
    align-items: center;
    & > * {
        margin: 0px 2rem;
    }
`;

function ToolPanel() {
    return (
        <StyledToolsCnt>
            <PinPicker />
            <ShapeSelect />
            <SizeSelect />
        </StyledToolsCnt>
    );
}

export default ToolPanel;

// src/components/ToolPanel.vue
<template>
    <div class="tool-panel">
        <PinPicker :pinShape='shape' :palette="[]"/>
        <ShapeSelect :value="shape" @change="onShapeChange"/>
        <SizeSelect :value="size" @change="onSizeChange"/>
    </div>
  </template>

<script lang="ts">
import { defineComponent, PropType } from 'vue'
import SizeSelect from './SizeSelect.vue';
import ShapeSelect from './ShapeSelect.vue';
import PinPicker from './pinPicker/PinPicker.vue';
import { MosaicSize, PinShape } from '@/utils/mosaicTypes';

export default defineComponent({
  name: 'tool-panel',
  emits: ['sizeChange', 'shapeChange'],
  props: {
    size: String as PropType<MosaicSize>,
    shape: {
      type: String as PropType<PinShape>,
      required: true
    }
  },
  components: {
    SizeSelect,
    ShapeSelect,
    PinPicker
  },
  methods: {
    onSizeChange (newValue: MosaicSize) {
      this.$emit('sizeChange', newValue);
    },
    onShapeChange (newValue: PinShape) {
      this.$emit('shapeChange', newValue);
    }
  }
})
</script>
<style scoped lang="scss">
    .tool-panel{
        padding: 1rem;
        display: flex;
        justify-content: center;
        align-items: center;
        & > *{
            margin: 0 2rem;
        }
    }
</style>
